import 'package:aoc/logger.dart';
import 'package:test/test.dart';
import 'package:aoc/solutions/index.dart';

void main() {
  initializeLogging("verbose");
  test('Day11', () async {
    String input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....""";
    int expectation = 374;
    var day = Day11(input);
    expect(day.solvePartA(), expectation);
  });

  test('Day11 - Part B simple', () async {
    String input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....""";

    var day = Day11(input);
    expect(day.solvePartB(extensionFactor: 2), 374);
  });

  test('Day11 - Part B', () async {
    String input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....""";

    var day = Day11(input);
    expect(day.solvePartB(extensionFactor: 3), 456);
    expect(day.solvePartB(extensionFactor: 10), 1030);
    expect(day.solvePartB(extensionFactor: 100), 8410);
  });

  test('Day11 - helper', () async {
    String input = """.....#..........
...........#....
#...............
................
................
................
..........#.....
.#..............
...............#
................
................
................
...........#....
#.....#.........""";
    int expectation = 456;
    var day = Day11(input);
    expect(day.solvePartA(simulateExtension: false), expectation);
  });
}
