image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies + test
    init: |
      dart pub get
      dart test

vscode:
  extensions:
    - dart-code.dart-code
    - GitHub.vscode-pull-request-github
    - usernamehw.errorlens
    - spmeesseman.vscode-taskexplorer
