name: Update readme ⭐️ progress

on:
    # !Please set a different minute than 51 if you enable this!
    # schedule:
    #      - cron: "17 */6 * * *" # Every 6 hours
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ vars.AOC_ENABLED }}
              with:
                ref: main
                token: ${{ secrets.PAT }}
            - uses: k2bd/advent-readme-stars@v1
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ vars.AOC_ENABLED }}
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ vars.AOC_YEAR }}
                  leaderboardId: ${{ secrets.AOC_LEADERBOARD_ID }}
            - uses: joblo2213/aoc-badges-action@v3
              with:
                  userid: ${{ secrets.AOC_USER_ID }}     # your user id, see setup on how to obtain
                  session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain      
                  year: ${{ vars.AOC_YEAR }}
                  leaderboard: 'https://adventofcode.com/${{ vars.AOC_YEAR }}/leaderboard/private/view/${{ secrets.AOC_LEADERBOARD_ID }}.json'
          #         Optional inputs:
          #         
          #         year: 2021                                                                                     # The year for which stats should be retrieved
          #         leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/00000.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          #         dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20📅-)[0-9]+(?=-blue)'                   # Regular expression that finds the content of the day badge in your file.
          #         starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          #         daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.
            - uses: stefanzweifel/git-auto-commit-action@v5
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ vars.AOC_ENABLED }}
              with:
                  commit_message: "update readme progess"
                  push_options: --force
                  branch: main